### ISSUE TITLE
 wrong permissions in tmp

### ISSUE THREAD

**Issue by mricim** [Tob1asDocker/php#2]
Hello,
I was using the `tobi312/php:8.0-fpm-nginx-alpine` image and I have found this problem `[crit] 15#15: *4 open() "/var/lib/nginx/tmp/client_body/0000000001" failed (13: Permission denied),` , my solution has been this `chgrp -R nginx /var/lib/nginx`, it also works with this `chmod -R 755 /var/lib/nginx`

**Comment by Tob1as** [comment]
Hello,

i have fixed it with `chown -R www-data:www-data /var/lib/nginx/`[*](https://github.com/Tob1asDocker/php/blob/7487a339a8ac7faf84e509aa25260ac6e0b92af0/alpine.x86_64.8_0_fpm_nginx.Dockerfile#L28), because nginx run as www-data user[*](https://github.com/Tob1asDocker/php/blob/7487a339a8ac7faf84e509aa25260ac6e0b92af0/alpine.x86_64.8_0_fpm_nginx.Dockerfile#L29). I have test it with a [simple php upload](https://gist.github.com/taterbase/2688850) script.
