### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by Effectivity** [Tob1asDocker/php#3]
Hello!

Could you add support for PHP 8.1 FPM version?

Thanks for that!

**Comment by xShazzy** [comment]
no

**Comment by xShazzy** [comment]
@Cararr don't pajacuj

**Comment by Tob1as** [comment]
I'm working on it (see branch "new"). 

I am planning PHP 7.4, 8.0 and 8.1 images for amd64, arm64 and arm32v7. But compiling php extension takes a long time especially for arm arch and I have to check that it doesn't break via docker hooks or github-actions.

**Comment by Tob1as** [comment]
All of my Image now with PHP 8.1.  
Currently i have only tested the apache and nginx images, but the others should work as well.  
The longest construction time of an image was 3h with github action.

I thought about not supporting 8.0 and 7.4 anymore, because 7.4 is end of life and 8.0 is no longer actively supported.
https://endoflife.date/php
